[phases.setup]
nixPkgs = ["nodejs_22", "yarn"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "npx http-server build -p 8080 -c-1 --cors -g -S"

